services:
  - type: web
    name: voicescript-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_KEY
        sync: false
      - key: OPENROUTER_KEY
        sync: false
